[env:TX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM9
monitor_port = COM9
build_src_filter = 
    +<*>          ; Neem eerst alle bestanden op (handig als je later gedeelde .h/.cpp bestanden hebt)
    -<main_rx.cpp> ; Sluit expliciet de code voor de ontvanger UIT

[env:RX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM10
monitor_port = COM10
build_src_filter =
    +<*>          ; Neem eerst alle bestanden op
    -<main_tx.cpp> ; Sluit expliciet de code voor de zender UIT