[env:MASTER]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DROLE_MASTER
upload_port = COM9
monitor_port = COM9
monitor_speed = 2000000
monitor_filters = echo, send_on_enter
build_src_filter = 
    +<*>            ;
    -<main_tx.cpp>  ;
    -<Universal_TimeReversal_Phase1_Test.cpp>  ;
    -<main_rx.cpp>  ;
    -<slave.cpp>    ;

[env:SLAVE]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DROLE_SLAVE
upload_port = COM10
monitor_port = COM10
monitor_speed = 2000000
build_src_filter = 
    +<*>            ;
    -<main_tx.cpp>  ;
    -<Universal_TimeReversal_Phase1_Test.cpp>  ;
    -<main_rx.cpp>  ;
    -<master.cpp>   ;
