; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:board_A]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
upload_port = COM13  ; <-- BELANGRIJK: de poort voor je eerste board
monitor_port = COM13   ; <-- BELANGRIJK: de poort voor je eerste board

[env:board_B]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4  ; <-- BELANGRIJK: de poort voor je tweede board
monitor_port = COM4   ; <-- BELANGRIJK: de poort voor je tweede board